### PR TITLE
Improve error logging

### LINKED ISSUE #3: Improve error logging
Currently the command-line tool `apg.sh` first outputs errors in the input grammar, then lists the complete input, which can be rather long.

It took me a while to realize that the tool gives more hints on the errors than just
~~~
EXCEPTION THROWN: Error: apg.js: grammar has syntax errors
~~~
because the detailed error message was scrolled out of sight 😄 

It would improve use on the command-line if the error details would be written _after_ the input grammar.

This change is proposed in #4

### PR DESCRIPTION
**Pull request by ralfhandl**
Fixes #3

### CODE REVIEW

**Comment by ldthomas** [comment]
Thanks for your keen eye. Much appreciated.

**Comment by ralfhandl** [comment]
Thanks for providing `apg-js` and the helpful [examples](https://github.com/ldthomas/apg-js-examples), I'm pasting together what I need from there 😄

**Comment by ldthomas** [comment]
My pleasure. Very rewarding to know that it is useful to a live project out there. Since JavaScript doesn't seem to provide a native XML parser, I'm in the process of adding one to apg-js now. No promises, but I would be open to other suggestions as well.

**Comment by ralfhandl** [comment]
I'm using [sax js](https://www.npmjs.com/package/sax) in [odata-csdl](https://github.com/oasis-tcs/odata-csdl-schemas/tree/master/lib) - no dependencies, easy to use, very popular.

**Pull request merged**
